mabreyes/marcreyes.ph

- assets/css/main.css
- assets/js/contact-form.js
- index.html
This pull request provides addition of components and features to the contact form.
> Additional form components and features

- assets/css/main.css
- index.html
Add breakpoint for much smaller screens.
> Add breakpoint for much smaller screens

- index.html
This pull request update e-mail invalid notification.
> Update e-mail invalid notification

- _redirects
- index.html
> Add a netlify redirect config

- _redirects
> Update redirect rules

- 404.html
- _redirects
Fix on unresolved redirects in _redirects file
> Fix on unresolved redirects

- 404.html
- index.html
> Update refresh meta

- about/index.html
Add a new /about page on the website.
> Add an about page

- about/index.html
Prettify margins of about section
> Prettify margins

- 404.html
> Fix links on 404

- 404.html
- about/index.html
Implements an update on 404 error message and typed strings in about page
> Update error message and typed strings

- 404.html
- index.html
Signed-off by; Marc Anthony Reyes (<marcreyesmedia@gmail.com>)
Update blog links
> Update blog links

- index.html
> Update instagram link

- about/index.html
> Add new talks in about page

- index.html
> Added new keywords for SEO

- about/index.html
- css/main.css
- index.html
Signed-off-by: Marc Anthony B Reyes (<marcreyesmedia@gmail.com>)
Adds scroll progress bar to home and about.
> Add scroll progress bar

- .gitignore
- css/main.css
- package.json
Signed-off-by: Marc Anthony B Reyes (<marcreyesmedia@gmail.com>)
Migrate builds through parcel
> Migrate to parcel

- index.html
Signed-off-by: Marc Anthony B Reyes (<marcreyesmedia@gmail.com>)
Reverts to commit ```699e2e2```
> Revert to commit 699e2e2

- _includes/core/navigation.html
> Change GitHub to 🚀Projects

- 404.html
- index.html
> Update description in meta for seo

- README.md
> Update readme for open source

- css/main.css
> Increase font size on web browser

- _includes/head.html
- _layouts/default.html
- css/dark.css
- css/fonts/gtaem/stylesheet.css
- css/main.css
> New font because I change my mind a lot

- css/dark.css
- css/light.css
- index.html
> Implement dark mode and toggle

- css/dark.css
- css/light.css
> Remove background in navbar

- 404.html
- css/dark.css
- css/light.css
> Create 404 page 
